name: weather_service_ci
on: [push]
env:
  SERVER_NAME: weather_service
jobs:
  build:
    runs-on: ubuntu-latest
    container: maven
    steps:
      - run: echo "buiild and compile maven project"
      - run: mvn -v
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - run: mvn compile
  test:
    runs-on: ubuntu-latest
    container: maven
    steps:
      - run: echo "testing project"
      - run: mvn -v
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - run: mvn compile
      - run: mvn test -Dspring.profiles.active=dev